preview ready to go

diff --git a/preview b/preview
--- a/preview
+++ b/preview
@@ -1,73 +1,108 @@
 #!/usr/bin/env bash
-# preview a temporary pdf, removing the file after viewing
-# TODO option to save rendered pdf(s)
+# preview a pdf
+# Copyright (c) 2021 Julia
 
 preview() {
 	# make a temporary file, view it and remove it once viewed
+    local output_file
 	if [[ "${1:(-3)}" == pdf ]]; then
 		zathura -- "$1"
 		return
 	fi
-	if [[ "$save_file" ]]; then
-		output_file="test"
+    # if the keep flag is present, remove current file extension and replace with pdf
+	if [[ "${opts[*]}" == *"-k"* ]]; then
+		output_file="${1%.*}.pdf"
+        local preserve=true
 	else
 		output_file="$( mktemp --suffix='.pdf' )"
 	fi
-	pandoc "$1" -o "${output_file}"
-	zathura -- "${output_file}" && rm -- "${output_file}"
-}
 
-print_error() {
-	tput setaf 1
-	printf -- '[ERR] %s\n' "$1" >&2
-	tput sgr0
+    # generate the file and open it, exit on failure
+	pandoc "$1" -o "${output_file}" 2>/dev/null || print_error "Cannot use '$1'. Does it exist?"
+	zathura -- "${output_file}" || print_error "Operation failed!"
+    if [[ ! "$preserve" ]]; then
+        rm -- "${output_file}"
+    fi
 }
 
 main() {
 	# check for arguments and run preview() on every valid file given
-	if [[ "$#" ]]; then
-		while (( $# )); do
-			preview_file="$1"
-			if [[ -s "${preview_file}" ]]; then
-				preview "${preview_file}"
+    parse_args "$@"
+
+    # declare arrays for args and opts, sort provided arguments accordingly
+    declare -a args opts
+    for arg in "$@"; do
+        if [[ $arg == [-]* ]]; then
+            opts+=("$arg")
+        else
+            args+=("$arg")
+        fi
+    done
+
+    local preview_file 
+    # if the user provided files to operate on, iterate through them
+    if (( "${#args[@]}" > 0 )); then
+		for f in "${args[@]}"; do
+			if [[ -s "${f}" ]]; then
+				preview "${f}"
 			else
-				print_error "Cannot access file '${preview_file}'"
+				print_error "Cannot access file '${f}'"
 			fi
 			shift
 		done
+    # otherwise, select files interactively
 	else
-		preview_file="$( find "${HOME}" -type f | fzf +m )"
+		preview_file="$( find "." -type f | fzf +m )" || exit 0
 		preview "${preview_file}"
 	fi
-
-	unset preview_file
-	unset output_file
 }
 
-# TODO finish implementing getopt
+print_error() {
+    # print errors to stderr
+	tput setaf 1
+	printf -- '[ERR] %s\n' "$1" >&2
+	tput sgr0
+    exit 1
+}
+
+usage() {
+    # usage
+    cat << EOF
+Usage: preview [<args>] [file]
+
+Arguments are:
+    -h, --help    Display this help
+    -k, --keep    Save the generated pdf
+    -r, --readme  Preview the README of the current directory
+EOF
+exit 0
+}
+
 parse_args() {
-	TEMP="$( getopt --options :hs --longoptions help,save --name "$0" -- "$@" )"
+    # parse arguments
+	TEMP="$( getopt -o 'hkr' -l 'help,keep,readme' -n "preview" -- "$@" )"
 	eval set -- "$TEMP"
 	unset TEMP
 
 	while true; do
 		case "$1" in
-			-h|--help)
-				printf -- '%s\n' "Help"
-				exit 1
+			'-h'|'--help')
+                usage
 				;;
-			-s|--save)
-				save_file="ON"
-				printf -- '%s\n' "$save_file"
-				unset save_file
-				exit 2
+			'-k'|'--keep')
+                shift
+                continue
 				;;
+            '-r'|'--readme')
+                preview "./README.md"
+                exit 0
+                ;;
 			'--')
 				shift
 				break
 				;;
 			*)
-				printf -- '%s\n' "Other"
+				print_error "$2 is not a recognized argument"
 		esac
 	done
 }
