formatting concistency

diff --git a/u b/u
--- a/u
+++ b/u
@@ -1,10 +1,11 @@
 #!/usr/bin/env bash
 set -euo pipefail
+
 # update system on arch, calls aur sep w extra util for aux programs (date-based) at end
 # requires informant, pacman-contrib and yay
 
 printPacdiff () {
-	if [ "$PACDIFF_RUN" -eq 0 ] && [ -s /tmp/pacnew.out ]; then
+	if [[ "${PACDIFF_RUN}" -eq 0 ]] && [[ -s /tmp/pacnew.out ]]; then
 		printf -- "\\nPacnew files: %s\\n" "$( cat /tmp/pacnew.out )"
 		PACDIFF_RUN=1
 		return
@@ -16,11 +17,16 @@ printPacdiff () {
 
 PACDIFF_RUN=0
 
+if [[ "$( id -u )" -ne 0 ]]; then
+	printf -- "Error! Do not run as root.\\nCancelling...\\n"
+	exit 1
+fi
+
 informant check; INF_UPDATES=$?
-if [[ $INF_UPDATES != 0 ]]; then
+if [[ ${INF_UPDATES} -ne 0 ]]; then
 	informant list
 	printf -- 'Read new bulletins? '; read -r response
-	case $response in
+	case "$response" in
 	    y|Y)
 		informant read	;;
 	    *)
@@ -31,12 +37,12 @@ else
 fi
 
 printf -- ':: Proceed with main update? [Y/n] '; read -r response
-case $response in
+case "$response" in
     y|Y)
 	pacman -Syu
 	pacdiff -o > /tmp/pacnew.out
 	printf -- ':: Also update AUR packages? [Y/n] '; read -r response
-	case $response in
+	case "$response" in
 	    y|Y)
 		sudo -u jam yay -Syua  ;;
 	    *)
@@ -50,8 +56,9 @@ printPacdiff
 
 lastDate=$( cat /home/jam/bin/.lastDate )
 currentDate=$(date "+%y%m%d")
+nextDate=$(( lastDate + 7 ))
 # TODO Kill sudo when entering here to negate the extra sudo calls
-if [ $(( lastDate + 7 )) -lt "$currentDate" ]; then
+if [[ "${nextDate}" -lt "${currentDate}" ]]; then
     sudo -u jam zsh /home/jam/bin/runZinit.sh
     sudo -u jam /usr/bin/tldr --update
 	sudo -u jam vim +PluginInstall +qall
@@ -62,14 +69,14 @@ if [ $(( lastDate + 7 )) -lt "$currentDate" ]; then
 	printf -- 'Npm updated.\n'
 	paccache -d
 	printf -- ':: Clear pacman cache? [Y/n] '; read -r response
-	case $response in
+	case "$response" in
 		y|Y)
 			paccache -rv  ;;
 		*)
 			printf -- 'Pacman cache cleared.\n'
 		esac
-    printf -- "%s\\n" "$currentDate" > /home/jam/bin/.lastDate
-    printf -- "Next full update will run on or after %d.\\n" "$(( currentDate + 7 ))"
+    printf -- "%s\\n" "${currentDate}" > /home/jam/bin/.lastDate
+    printf -- "Next full update will run on or after %d.\\n" "${nextDate}"
 	printPacdiff
 # TODO Add updater for cargo and checks for if anything here fails
 #      this can be `if [ cmd ]; then \nprintf --'cmd updated\n'`
